k8s:
  url: https://10.168.1.121:6443
  token: cab559c45557a8f65868945cd9ce6bad
spring:
  jpa:
    show-sql: true   #打印sql
  datasource:
    url: jdbc:h2:mem:xwj_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE   #mem：连接到内存
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
#    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
logging:
  level:
    root: INFO