k8s:
  url: https://10.168.1.121:6443
  token: cab559c45557a8f65868945cd9ce6bad
spring:
  jpa:
    show-sql: true   #打印sql
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      username: root
      password: 123456
      schema-locations:
        -  classpath*:schema.sql
  datasource:
    url: jdbc:h2:./db/k8s;AUTO_SERVER=TRUE;
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: true
      path: /h2-console
logging:
  level:
    root: INFO