k8s:
#  url: https://10.168.1.121:6443
#  token: cab559c45557a8f65868945cd9ce6bad
#  url: https://172.16.100.1:6443
#  token: 92b863fe8615861251e5faf8881006c6
#  url: https://172.16.100.10:6443
#  token: b4ce7e4bf21075c0cc8e56752088503c
#  url: https://10.168.1.200:6443
#  token: f86af79b892f7797105064676935eee6
  url: https://kubernetes.docker.internal:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJuLUFQVTUzTC1sdndva3d1aVFkcXRDcFpPcmdXYXd1T0Z1YWxnSWZSdmcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrOHMtYWRtaW4tdG9rZW4tc2xwaGgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiazhzLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNzVjNTMxNTgtZGY0Yy00MjJmLWFlOWItYWI0ODcwZmVjMjU5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOms4cy1hZG1pbiJ9.mQZ5M75pSX9PxWpXMEk0qF2TSQOn4ToyKBQfLXWyswLszfwfeYD9Gz-EF9cSQRSF6vLucSoGfEJwJJjUFxNd_M59T9Tc7ZbLvaIULeFqEhrkeMO8DrFvw-ci7OhmgZMJO5s13oNDJLhqyP4pplLUCaUU-TMNvTxrwuSt7tEDPyJWH_P9nG45GFmRgBURBJpYFXgvI8v5ud06zKA7lgdx_FMoNlHgvXFWxBZHLN-_MiEXg5Edg_Sol9KwUaoKQ0OQoZyZG9tVD652qnuQyvHc7l6vu7w6AwKIw0KKZX9w6A602QjutKCgjaExRgLJuI6ANRpFvzYw73bJ3yKT3cL7yQ
server:
  port: 8080
  address: 127.0.0.1
spring:
  jpa:
    show-sql: false   #打印sql
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      username: root
      password: 123456
      schema-locations:
        -  classpath*:schema.sql
  datasource:
    url: jdbc:h2:./db/k8s;AUTO_SERVER=TRUE;
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: true
      path: /h2-console
logging:
  level:
    root: INFO